CREATE DATABASE QLBN_IT64B
USE QLBN_IT64B

--Bảng Bác sĩ
CREATE TABLE BAC_SY (
	MABS INT NOT NULL PRIMARY KEY,
	TENBS NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(200) NOT NULL,
	SODIENTHOAI CHAR(10) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL
);

--Bảng Bệnh
CREATE TABLE BENH (  
	MABENH INT NOT NULL PRIMARY KEY,
	TENBENH NVARCHAR(50) NOT NULL
);

--Bảng Bệnh nhân
CREATE TABLE BENH_NHAN (
	MABN INT NOT NULL PRIMARY KEY,
	TENBN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(200) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	SOGIUONG CHAR(10) NOT NULL,
	SOBUONG CHAR(10) NOT NULL,
	DOITUONG NVARCHAR(200) NOT NULL,
	YEUCAUKHAM NVARCHAR(200)
);

--Bảng Dịch vụ
CREATE TABLE DICH_VU (
	MADV INT NOT NULL PRIMARY KEY,
	TENDV NVARCHAR(50) NOT NULL,
	DONGIA FLOAT NOT NULL,
	DONVITINH CHAR(10) NOT NULL
);

--Bảng Khoa
CREATE TABLE KHOA (
	MAKHOA INT NOT NULL PRIMARY KEY,
	TENKHOA NVARCHAR(50) NOT NULL,
);

--Bảng Phiếu thuốc
CREATE TABLE PHIEU_THUOC (
	SOPHIEUTHUOC INT NOT NULL PRIMARY KEY,
	NGAYKEDON DATE NOT NULL,
	TENBS NVARCHAR(50) NOT NULL,
	TENBN NVARCHAR(50) NOT NULL,
	MATHUOC INT NOT NULL,
	SOLUONG INT NOT NULL,
);

--Bảng Nhân viên
CREATE TABLE NHAN_VIEN (
	MANV INT NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(200) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	SODIENTHOAI CHAR(10)
);

--Bảng biên lai thu viện phí
CREATE TABLE BIEN_LAI (
	SOBIENLAI INT NOT NULL PRIMARY KEY,
	TENBN NVARCHAR(50) NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	NGAYTHANHTOAN DATE NOT NULL
);

--Bảng Hồ sơ bệnh án
CREATE TABLE HO_SO (
	MAHS INT NOT NULL PRIMARY KEY,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE,
	CHIPHIDIEUTRI FLOAT,
	MAKHOA INT NOT NULL FOREIGN KEY REFERENCES KHOA(MAKHOA),
	MABN INT NOT NULL FOREIGN KEY REFERENCES BENH_NHAN(MABN),
	MABS INT NOT NULL FOREIGN KEY REFERENCES BAC_SY(MABS),
	KETQUADIEUTRI NVARCHAR(200)
);

--Bảng Phiếu khám bệnh
CREATE TABLE PHIEU_KHAM_BENH (
	MAPHIEU INT NOT NULL PRIMARY KEY,
	MAHS INT NOT NULL FOREIGN KEY REFERENCES HO_SO(MAHS),
	NGAYKHAM DATE NOT NULL,
	TRIEUCHUNG NVARCHAR(200) NOT NULL,
	TENBS NVARCHAR(200) NOT NULL,
	TENBN NVARCHAR(200) NOT NULL,
	TENBENH NVARCHAR(200) NOT NULL,
	CHIPHIKHAM FLOAT NOT NULL
);



--Insert bảng Bác sĩ
INSERT INTO BAC_SY(MABS, TENBS, DIACHI, SODIENTHOAI, GIOITINH, NGAYSINH) VALUES 
('1', N'Nguyễn Thị Vân', N'96 Chợ Hàng', '0974358741', N'Nữ', '1985-03-21');

SELECT * FROM BAC_SY



























-- INPUT DỮ LIỆU